version: "2.1"
services:
  db:
    image: "postgres:latest"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  chainlink:
    build: "chainlink/"
    restart: on-failure
    ports:
      - "6688:6688"
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable
      - ETH_URL=ws://${DOCKER_GATEWAY_HOST:-host.docker.internal}:8545
    volumes:
      - .:/host
